server {
    listen 80;
    server_name proxy.test;
    root /Users/michaelberger/Desktop/riveria-security-tool/.riveria-runtime/tmp-rp-txt/reverse-proxy/public;

    location / {
        proxy_pass http://127.0.0.1:8088;
    }
}
